### ISSUE TITLE
File-saving issues.What is right way to save files or just clean them?

### ISSUE THREAD

**Issue by pronan** [bungle/lua-resty-reqargs#2]
Win10 64.

I changed line 90 `temp = tmpname()` to `temp = 'c:\\tmp\\'..basename(d.filename)`, and send a `flag.jpg` and a `honeydew.xlsx`. Both are saved in the specified path with correct size but I can't open them. 

make a form like:

    <html lang='zh'>
        <head>
        </head>
        <body>
        <form enctype="multipart/form-data" method="post">
            <p>
                <label for="username">user</label>
                <input id="username" name="username" type="text" />
            </p>
    <p>
        <label for="files">File input</label>
        <input type="file" id="files" name="myfile">
    </p>
    <p>
        <label for="files1">File input2</label>
        <input type="file" id="files1" name="myfile1">
    </p>
            <input type="submit" value="submit"/>
        </form>
        </body>
    </html>

**Comment by bungle** [comment]
Hi, what do you mean that you can't open them (you don't have access to them? they are locked or something? or their content is corrupted?).

Have you checked that hashes match, eg:

```cmd
CertUtil -hashfile C:\tmp\flag.jpg MD5
```

And compare the hash to original.

I fear there is something strange going on on Windows, but I'm not sure what. I do not have Windows around.

**Comment by bungle** [comment]
> What is right way to save files or just clean them?

Well you should use:

1. https://www.lua.org/manual/5.1/manual.html#pdf-os.rename to move tmpname file to your preferred location
2. You should clean them with https://www.lua.org/manual/5.1/manual.html#pdf-os.remove (or just have cron, scheduled task, nginx timer etc. to cleanup old files from temp)

**Comment by pronan** [comment]
It's corrupted. It's a windows problem. I've also tried lua-resty-post which has the same issue. Seems to be a lua-resty-upload issue.
Later I found thant It's Ok in ubuntu. So never mind..Thanks for suggestions.
