### ISSUE TITLE
Consider adding support for empty file input.

### ISSUE THREAD

**Issue by pronan** [bungle/lua-resty-reqargs#3]
`local get, post, files = require"resty.reqargs"{}`
Now, if you post an empty form , the `get` and `post` would be `nil`, `files` would be an error infomation like `./html/: Permission denied'`. I think it would be better to ignore empty file value silently.

exmaple form:

    <html lang='zh'>
        <head>
        </head>
        <body>
        <form enctype="multipart/form-data" method="post">
            <p>
                <label for="username">user</label>
                <input id="username" name="username" type="text" />
            </p>
            <p>
                <label for="files">File input</label>
                <input type="file" id="files" name="myfile">
            </p>
            <p>
                <label for="files1">File input2</label>
                <input type="file" id="files1" name="myfile1">
            </p>
            <input type="submit" value="submit"/>
        </form>
        </body>
    </html>

**Comment by bungle** [comment]
Thanks, I will check this out.

**Comment by bungle** [comment]
@pronan,

I tried your example and didn't find this error. I posted empty form, and got this:

**get**:

```lua
{}
```

**post:**

```lua
{username="",n=0}
```

(small bug here `n==0`, should be 1).

**files:**

```lua
{
    myfile1={
        size=0,
        type="application/octet-stream",
        file="",
        name="myfile1",
        temp="/tmp/lua_Bq0ZME"
    },
    myfile={
        size=0,
        type="application/octet-stream",
        file="",
        name="myfile",
        temp="/tmp/lua_qxcVly"
    },
    n=0
}
```

(small bug here `n==0`, should be 2).

So I think you don't have write access to html directory, and it seems you have modified the source or something.

**Comment by bungle** [comment]
Btw. I also pushed a new version of this that fixes some rare issues if you have multiple fields with same name.

**Comment by pronan** [comment]
Sorry dude.I do change a line to save the file to a specific path. I forgot that.
